# Self-contained profile for this exercise
g1_oulad:
  target: local
  outputs:
    local:
      type: clickhouse
      host: clickhouse          # use the service name in docker-compose
      port: 8123
      user: ftw_user
      password: ftw_pass
      schema: mart              # ClickHouse "database". For isolation you can set ftw_myk01
      threads: 4
      secure: false

    remote:
      type: clickhouse
      host: 54.87.106.52        # your server IP/DNS
      port: 8123
      user: ftw_user
      password: ftw_pass
      schema: mart
      threads: 4
      secure: false
